### PR TITLE
Add LFA button and speed limit signal for newer Hyundai cars.

### PR DESCRIPTION
**Pull request by mob9221**
This PR adds the message containing speed limit data that is shown on some Hyundai navigation systems, gauge clusters and heads up displays.

### CODE REVIEW

**Comment by oricalworks** [comment]
Does this work for 2018 Kia Stinger?
I kept getting the max returned value of 255 all the time.

**Comment by gregjhogan** [comment]
I took a look at some routes for a 2020 sonata and 2020 palisade and I couldn't find a place where the value of the first byte of 0x544 changed (always 255 with openpilot running, stock drive for palisade always 0)

A while ago I did find address 0x255 is what the camera uses to determine how to adjust the set speed for HDA mode.  Note that this message sometimes uses the same bytes to mean different things and the speed limit changes are in the future (something in the message somehow indicates how far in the future)
https://github.com/gregjhogan/panda/blob/examples/examples/hda_test.py

**Comment by mob9221** [comment]
> I took a look at some routes for a 2020 sonata and 2020 palisade and I couldn't find a place where the value of the first byte of 0x544 changed (always 255 with openpilot running, stock drive for palisade always 0)
> 
> A while ago I did find address 0x255 is what the camera uses to determine how to adjust the set speed for HDA mode. Note that this message sometimes uses the same bytes to mean different things and the speed limit changes are in the future (something in the message somehow indicates how far in the future)
> https://github.com/gregjhogan/panda/blob/examples/examples/hda_test.py

Hi Greg, I just thought it would be size 8 since it is most likely used for HDA_VSetReq in the dbc which is also 8 bits but I doubt we can find a speed limit sign to push it that far. I tried getting HDA to work again on these cars since its blocked by the panda I believe but just setting HDA_VSetReq didn't do the trick as I thought it would. Thanks for sharing the example I'll dig into it further.

**Comment by jason-wen-waysun** [comment]
Can confirm the new signal for the LFA button is working on the 2021 Hyundai Sonata N Line.

**Comment by sunnyhaibin** [comment]
Can confirm the signal for the LFA button is working on the 2021 Hyundai Sonata N Line.

**Comment by gregjhogan** [comment]
`SpeedLim_Nav_Clu` is the speed limit displayed on the cluster for what vehicles and on what CAN bus?

at one point I had openpilot on my 2020 palisade always putting the car in HDA mode (had longer resume timeout when stopped behind a lead) and I believe with that code just changing `HDA_VSetReq` worked to change the set speed but can't remember for sure (I never had anything automatically changing the speed with speed limits)
https://github.com/gregjhogan/openpilot/commits/hyundai-hda

**Comment by mob9221** [comment]
> `SpeedLim_Nav_Clu` is the speed limit displayed on the cluster for what vehicles and on what CAN bus?
> 
> at one point I had openpilot on my 2020 palisade always putting the car in HDA mode (had longer resume timeout when stopped behind a lead) and I believe with that code just changing `HDA_VSetReq` worked to change the set speed but can't remember for sure (I never had anything automatically changing the speed with speed limits)
> https://github.com/gregjhogan/openpilot/commits/hyundai-hda

I can't fully test which vehicles it is available on but it seems to be any vehicle with HDA and the new nav units from Hyundai (AVN5). I didn't see the HDA_C_State message before, Were these messages  changed / removed in future dbc commits?

**Comment by gregjhogan** [comment]
2020 sonata and palisade limited have AVN5, correct?  I am not seeing anything in this message change (even looked at a stock palisade drive)

**Comment by mob9221** [comment]
I drive the 2020 sonata limited. Here is the cabana link. Have a look at Navi_HU starting around 195s. 

https://my.comma.ai/cabana/?route=6bc7319847dbb610%7C2021-08-17--20-40-36&seekTime=1&url=https%3A%2F%2Fchffrprivate-vzn.azureedge.net%2Fchffrprivate3%2Fv2%2F6bc7319847dbb610%2F6ceacc1a122001e70bd8f8869920e392_2021-08-17--20-40-36

**Comment by mob9221** [comment]
Hi @gregjhogan , could you explain what the data being sent in 
https://github.com/gregjhogan/panda/blob/examples/examples/hda_test.py
represents?

b"\x00\x00" + bytes([idx]) + b"\x00\x00\x30\x12\x6c"
This is the message being sent for HDA 55 mph in that example, but not sure which combination of bytes represent the actual speed.

**Comment by gregjhogan** [comment]
I have not found a way to get `SpeedLim_Nav_Clu` to output the speed limit on my vehicle :(

In the example script I believe the last two bytes were the speed limit (in some strange format) and the other bytes include a message type (address 0x255 is used for several messages of different types) and how far ahead the speed limit changes.  I believe the examples all set the distance ahead where the speed limit changes to zero (never figured out the distance format)

The way I tested it was by putting a panda in between the camera and the rest of the car (no openpilot) which forwarded all messages except 0x255, then the test script was used to inject 0x255 messages ad-hoc (sent to the camera) causing the camera to change the speed limit using `HDA_VSetReq`.

**Comment by james5294** [comment]
https://streamable.com/vh60oa

2022 Sonata seems to be getting Nav speed data, my 2021 Palisade still reads 0. Both n FW from june/july 2022.

**Pull request merged**
