### PR TITLE
CI: Fix panda CI by not upgrading Cython

### PR DESCRIPTION
**Pull request by jnewb1**
Cython 3.0.0 breaks opendbc, but now it wants to upgrade by default in the CI. Force to <3.0.0

### CODE REVIEW

**Comment by jnewb1** [comment]
https://github.com/commaai/panda/pull/1520

**Comment by sshane** [comment]
Found this PR which added it: https://github.com/cython/cython/pull/4013 Seems like a good warning to me, can we revert this? The real fix is removing the RuntimeError that has ambiguous behavior (and is being reverted)

**Comment by jnewb1** [comment]
> Found this PR which added it: [cython/cython#4013](https://github.com/cython/cython/pull/4013) Seems like a good warning to me, can we revert this? The real fix is removing the RuntimeError conversion that has ambiguous behavior (and is being reverted)

yea we can revert it. it would be nice if we had a better way to sync dependencies between openpilot and opendbc for ci

**Comment by jnewb1** [comment]
don't think we can revert this yet due to some weird paren choices in 3.0.0 __pyx_array_new (causes compile warning -> error)

visionipc/visionipc_pyx.cpp:9332:28: error: equality comparison with extraneous parentheses [-Werror,-Wparentheses-equality]
  if (((__pyx_v_c_mode[0]) == 'f')) {
       ~~~~~~~~~~~~~~~~~~~~^~~~~~
visionipc/visionipc_pyx.cpp:9332:28: note: remove extraneous parentheses around the comparison to silence this warning
  if (((__pyx_v_c_mode[0]) == 'f')) {
      ~                    ^     ~
visionipc/visionipc_pyx.cpp:9332:28: note: use '=' to turn this equality comparison into an assignment
  if (((__pyx_v_c_mode[0]) == 'f')) {
                           ^~
                           =
1 error generated.

**Pull request merged**
