### PR TITLE
Hyundai: sort DBC

### PR DESCRIPTION
**Pull request by sshane**
Done programmatically using https://pastebin.com/X8Ury0Rd. Should we add a test for this or do we not care to be that strict?

### CODE REVIEW

**Comment by rusefillc** [comment]
i love the idea of sorting DBC files for readability but those huge PRs need to be merged quickly to avoid a merge conflict like here, right?

@sshane do you have interest to resovle the merge conflict - maybe re-sort latest master content?

@adeebshihadeh is this PR a signal to empower more contributors to merge in order to improve average PR turn-around?

tagging @jyoung8607 just to add more to the fun

**Comment by rusefillc** [comment]
@sshane any chance you could programmatically sort more DBCs? Should that be a github action with auto-merge?

**Comment by sshane** [comment]
Yeah I would merge but I didn't see any interest in making all the DBCs sorted, plus the generated DBCs people usually look at wouldn't be sorted due to imports. @jyoung8607 know of any standard here with message address sorting?

**Comment by adeebshihadeh** [comment]
Closing because of the conflicts.

**Pull request closed without merging**
