### PR TITLE
VW MQB: Add detail to Blinkmodi_02

### PR DESCRIPTION
**Pull request by jyoung8607**
Add signals necessary for detecting comfort/convenience turn signal operation.

### CODE REVIEW

**Comment by Matheus-Garbelini** [comment]
Hi, what specific VW car this dbc file refers to?
Is it for all VW MQB cars? If so, what generation of VW MQB this is for?

**Comment by valentintintin** [comment]
@Matheus-Garbelini Hi !
I use this file for my Skoda Fabia MK3 (2017). A lot of signals work and other are never sent.
It depends of what you want to do :)

**Comment by Matheus-Garbelini** [comment]
Thanks @valentintintin 
So, in all cases you never get an undecoded signal with this DBC, is that so?

**Comment by jeroenveer** [comment]
This DBC Does not cover all signals, might be about 40%

**Comment by valentintintin** [comment]
> Thanks @valentintintin
> So, in all cases you never get an undecoded or unkown signal with this DBC, is that so?

What I would say it's : there are numerous signals decoded but not all of the DBC.
Moreover, some signals are on the DBC files but not transmited on the bus. 
For instance, `BO_ 391 EV_Gearshift: 8 XXX`. I have a DSG7 but this ID never appears. Same for LWI, EPS and others signals etc. I can give you a list of all my IDs if you want.

I'm starting it the world of car and reverse engineering. I've got a VCDS cable, maybe I'll we investigate more easily with it :)

**Comment by jeroenveer** [comment]
> 
> 
> > Thanks @valentintintin
> > So, in all cases you never get an undecoded or unkown signal with this DBC, is that so?
> 
> What I would say it's : there are numerous signals decoded but not all of the DBC.
> Moreover, some signals are on the DBC files but not transmited on the bus.
> For instance, `BO_ 391 EV_Gearshift: 8 XXX`. I have a DSG7 but this ID never appears. Same for LWI, EPS and others signals etc. I can give you a list of all my IDs if you want.
> 
> I'm starting it the world of car and reverse engineering. I've got a VCDS cable, maybe I'll we investigate more easily with it :)

EV is only on electric cars.

Messages are filtered by the Gateway so not all are visible on all can lines.

**Comment by Matheus-Garbelini** [comment]
Thanks all. The name of this DBC refers 2010, so I'm guessing this covered only MQB first generation, but skoda 2017 seems to be using second generation MQB (A0). I'm checking if this DBC would work with Audi A3 Mk3 since it seems to use first generation MQB.

@jeroenveer interesting, was this DBC generated using some specific EV car from VW then?

**Comment by jeroenveer** [comment]
All MQB are the same so this applies to your A3 as well.
Newer cars might have some more messages.

Some EV messages are on EV cars only
Some Diesel messages are on Diesel cars only

VW has just 2 CAN protocols that covers all, PQ for all 96> cars and MQB for all MQB cars.

**Comment by Matheus-Garbelini** [comment]
Thanks a lot @jeroenveer matching dbc files to the correct car model and year is still new to me.
@valentintintin do you happen to have a real can capture (perhaps saved on wireshark or other tool) so I can experiment with this dbc file? Currently I do not have access to any car.

**Comment by valentintintin** [comment]
@Matheus-Garbelini I can give you one dump this evening (I'm currently in holliday). I'll will record a part of my today's road with SavvyCan.
Notice that I'm plugged on the CAN Convenience bus (power train doesn't interests me).

**Comment by Matheus-Garbelini** [comment]
thanks a lot @valentintintin this would be really helpful :+1:

**Comment by valentintintin** [comment]
> thanks a lot @valentintintin this would be really helpful

There is my file : 
[dumpCanConvenienceSkoda2017.zip](https://github.com/commaai/opendbc/files/6976802/dumpCanConvenienceSkoda2017.zip)

There are 2 files : one with a lot of road at 90 km/h using ACC, air-conditioning, the second from engine stoped at an highway parking area followed by an insertion to 130 Km/h and an overtake of a car.

Have fun :)

**Comment by Matheus-Garbelini** [comment]
@valentintintin thank you so much. I'm going to test this with Scapy + canmatrix with this dbc file.

**Comment by Matheus-Garbelini** [comment]
@valentintintin thank you so much. I'm going to test this with Scapy + canmatrix with this dbc file.

**Comment by valentintintin** [comment]
@Matheus-Garbelini if you have any interesting results during the decoding, please let me know 😊

**Comment by Matheus-Garbelini** [comment]
@valentintintin what program you use to decode or save such captures?

**Comment by Matheus-Garbelini** [comment]
thanks @valentintintin , right now it appear that some unkown messages are also present there:
Screenshot_20210816_174509

**Comment by valentintintin** [comment]
@Matheus-Garbelini Yes I know and it could be good to decode them...

I don't know which ECU send messages with id starting 0x16 or 0x17. I'll try with VCDS to see if I can have more information.

I plan to try to decode messages for lights, air conditioning, lock etc. I never did it, it's like a challenge for me !

My goal is to have a good passenger HUD and why not control some functions of the car later.
https://twitter.com/valentinF4HVV/status/1426285076678070274?s=19

**Comment by Matheus-Garbelini** [comment]
@valentintintin that looks awesome. In my case I have to also try decoding some messages on some BMW car.
@jeroenveer do you happen to know which car model is the most well supported by the community in terms of DBC file completeness? I'm trying to find what car, which has a DBC file that is super easy to buy spare ECUs modules to do some standalone tests with its CAN communication. I'm guessing that some cars are more discussed than others in terms of hacking and those may have a DBC file more complete.

Thanks.

**Comment by jeroenveer** [comment]
I am only known in VAG group Canbus. The PQ DBC is pretty complete so you could target the Golf Mk6 for parts to test.

**Comment by jamiejones85** [comment]
Long shot, but does anyone have and PT/EV can logs for a VW (GTE/Egolf/ect) on charge and/or driving?

**Pull request merged**
