### PR TITLE
Honda: add alt gears for Thai HR-V hybrid

### PR DESCRIPTION
**Pull request by AlexandreSato**
Thai HR-V hybrid from 1e4baee1aa2687a0  (somkanae #5442 on Discord) use this alternative gears message.

example: https://connect.comma.ai/1e4baee1aa2687a0/1681388939939/1681389421367

### CODE REVIEW

**Comment by sshane** [comment]
Would you like to open a PR to auto-detect the gear message (in openpilot)? Then we can make future car ports easier and clean up the DBCs!

**Comment by AlexandreSato** [comment]
Yes!  Do you mean in the case of Honda or platforms in general?



Em 21 de abr. de 2023, à(s) 01:53, Shane Smiskol ***@***.***> escreveu:

﻿

Would you like to open a PR to auto-detect the gear message (in openpilot)? Then we can make future car ports easier and clean up the DBCs!

**Comment by AlexandreSato** [comment]
> Would you like to open a PR to auto-detect the gear message (in openpilot, just check the address for all the gears)? Then we can make future car ports easier and clean up the DBCs!
> 
> I don't know offhand if the same address gear messages also have the same definition across DBCs, so you'd want to check that (all `419 GEARBOX` msgs are same len and same signal definitions for example).

The signal definitions are different here is an example:
Honda Civic EX 2022:
```
BO_ 419 GEARBOX_ALT: 8 XXX
 SG_ GEAR : 7|8@0+ (1,0) [0|255] "" XXX
 SG_ GEAR_SHIFTER : 29|6@0+ (1,0) [0|63] "" XXX
 SG_ CHECKSUM : 59|4@0+ (1,0) [0|3] "" XXX
 SG_ COUNTER : 61|2@0+ (1,0) [0|3] "" XXX
 ```
 
honda_crv_executive_2016:
```
BO_ 419 GEARBOX: 8 PCM
 SG_ COUNTER : 61|2@0+ (1,0) [0|3] "" EON
 SG_ CHECKSUM : 59|4@0+ (1,0) [0|3] "" EON
 SG_ GEAR_SHIFTER : 29|6@0+ (1,0) [0|63] "" EON
 SG_ GEAR : 7|8@0+ (1,0) [0|255] "" EON
 ```
 
 honda_odyssey_exl_2018:
```
BO_ 419 GEARBOX: 8 PCM
 SG_ GEAR : 7|8@0+ (1,0) [0|256] "" EON
 SG_ GEAR_SHIFTER : 35|4@0+ (1,0) [0|15] "" EON
 SG_ COUNTER : 61|2@0+ (1,0) [0|3] "" EON
 SG_ CHECKSUM : 59|4@0+ (1,0) [0|3] "" EON
 ```

**Comment by sshane** [comment]
How about just detecting for the radarless platform to start? Combining the older signals will likely require me to check lots of data like I did before

**Pull request merged**
