### PR TITLE
Ford: Add LateralMotionControl

### PR DESCRIPTION
**Pull request by incognitojam**
Used for lane centering in 2018+ vehicles.

### CODE REVIEW

**Comment by incognitojam** [comment]
Screenshot from 2021-11-09 22-10-41

**Comment by adeebshihadeh** [comment]
Cool, does your Ford have the LKAS lockout?

**Comment by incognitojam** [comment]
@adeebshihadeh Yeah mine does too. This is for the Lane Centering/Traffic Jam Assist feature though, which uses a different command

**Comment by adeebshihadeh** [comment]
Ah, does this command have a lockout?

**Comment by incognitojam** [comment]
It's being investigated :)

**Pull request merged**
