### PR TITLE
Toyota: unify Lexus NXH, Lexus RXH, HighlanderH, Rav4H dbc, rename dbc to TNGA-K Hybrid

### PR DESCRIPTION
**Pull request by cydia2020**
basically the same as rav4h

### CODE REVIEW

**Comment by cydia2020** [comment]
image

**Comment by cydia2020** [comment]
@adeebshihadeh let me know if you want me to merge this with #504 , all affected cars are TNGA-K cars in both PRs, though the DBC for TNGA-K hybrid and TNGA-K ICE are distinct.

**Comment by adeebshihadeh** [comment]
Hmm, it turns out a couple of the Toyota DBCs are literally the same.
```
batman:toyota$ md5sum * | sort
0d60e80e68bbd0e09456ea4016c64291  _comma.dbc
0f5a92646f127c92f150401183345a20  _toyota_nodsu_common.dbc
11989779bdfaa1b8e764b98af048d216  lexus_is_2018_pt.dbc
16ac9b574b985274e416f3b893738055  lexus_nx300h_2018_pt.dbc
16ac9b574b985274e416f3b893738055  lexus_rx_hybrid_2017_pt.dbc
19598fe96fe8a1e2b2382b99bfc82e83  _toyota_2017.dbc
1ebc2755573b9d7c0036cd8eddd0f803  lexus_ct200h_2018_pt.dbc
202c4511c7f4c949829d64b723ccf7cf  toyota_nodsu_pt.dbc
5667382c97193e93652b23b9cbfc0435  lexus_nx300_2018_pt.dbc
7f522a57f862fba6604d1c73156189b4  toyota_corolla_2017_pt.dbc
8830bfa8f427af7fa19534f8f84823a4  toyota_avalon_2017_pt.dbc
8830bfa8f427af7fa19534f8f84823a4  toyota_highlander_2017_pt.dbc
922a18a9c164dd779f6dab729f2ddcec  toyota_highlander_hybrid_2018_pt.dbc
98037aed0549bc130de74e111a003cf9  toyota_prius_2017_pt.dbc
9bb56f2dbf0854fcb1a0c190bacdaff9  toyota_rav4_2017_pt.dbc
b5fce48ff81f89ba7e93ba46ddb3df98  lexus_gs300h_2017_pt.dbc
b85d08ebbb780e0ff08ee2ad05834d1e  toyota_rav4_hybrid_2017_pt.dbc
c0527528523bc049eeff6a233f35f812  toyota_sienna_xle_2018_pt.dbc
d2eb58fc77c9ba8d15ff9ab27983bb2a  toyota_nodsu_hybrid_pt.dbc
f282cb50f5bc3aa0bc417dc9977451a9  lexus_rx_350_2016_pt.dbc
```

**Comment by adeebshihadeh** [comment]
Nice work. I made the DBC name a bit simpler, but I'm open to changing it back if you had a specific reason. Feel free to also put a comment at the top of the DBC to describe the platform it's for.

**Pull request merged**
