### PR TITLE
Hyundai CAN Longitudinal: Enable for Camera SCC cars

### PR DESCRIPTION
**Pull request by sunnyhaibin**
**Description**

openpilot longitudinal control support for CAN-based HKG cars that have the following messages send from the car on bus 2:
- `SCC11`
- `SCC12`
- `SCC13`
- `SCC14`
- `FCA11`
- `FCA12`

Currently with 2022 Hyundai Kona EV, without radar disable. As the messages send from the car on bus 2, we block the messages and send our own longitudinal commands to bus 0.

`FCA11` and `FCA12` do stock FCW and AEB, and are forwarded from the LKAS camera to the car.

**Supersedes**
- https://github.com/commaai/openpilot/pull/26090/files

**Requires**
- https://github.com/commaai/panda/pull/1107

### CODE REVIEW

**Comment by sunnyhaibin** [comment]
Route with stock FCW active: `d3a039910163c67a/000000cb--b5898024e5`

image

**Comment by sunnyhaibin** [comment]
Another working test route: `ecb854b94fdfa4d5/00000001--70960afd85`

**Comment by sunnyhaibin** [comment]
Test route with stock AEB actively braking for the car! `d3a039910163c67a/000000d1--754d5d6111`
image

**Comment by adeebshihadeh** [comment]
I resolved the conflict, but can't push to the branch because it's from the sunnypilot org. Can you add write access for me, shane, and jason to the repo you're gonna make PRs from?

**Review by adeebshihadeh — APPROVED** [review]

**Comment by sunnyhaibin** [comment]
> I resolved the conflict, but can't push to the branch because it's from the sunnypilot org. Can you add write access for me, shane, and jason to the repo you're gonna make PRs from?

Invitation sent!

**Comment by sshane** [comment]
Fails test_models in openpilot: https://github.com/commaai/openpilot/actions/runs/11966321616/job/33361765473

**Comment by sunnyhaibin** [comment]
@adeebshihadeh @sshane Reopened https://github.com/commaai/opendbc/pull/1563 with fix.

**Pull request merged**
