### PR TITLE
Nissan: Add fingerprint for 2020 Altima

### PR DESCRIPTION
**Pull request by JtMotoX**
add missing fingerprint for 2020 Altima

route: `8864973010c8382c/00000000--ce17b8b109`

### CODE REVIEW

**Comment by jyoung8607** [comment]
We shouldn't really add any more CAN fingerprints unless we have to, we should add UDS firmware fingerprints. See fingerprinting 2.0:

https://github.com/commaai/openpilot/wiki/Fingerprinting

If you're not seeing UDS fingerprint data you're otherwise having trouble, let us know here or reach out on Discord.

**Comment by JtMotoX** [comment]
From what I can tell, the FW info pulled from my logs (snippet below) matches what is already in the  [fingerprints.py](https://github.com/commaai/opendbc/blob/5d258ce7c482f1c73560f4ae762badb4eba44ca5/opendbc/car/nissan/fingerprints.py#L32C3-L45C4), however, openpilot said my car is unsupported and was put in dashcam mode. Once I added the CAN fingerprints, openpilot recognized the car and allowed me to calibrate and use it.

```py
'carFw': [{'address': 1799,
          'brand': 'nissan',
          'bus': 0,
          'ecu': 'fwdCamera',
          'fwVersion': b'284N86CA1D',
          'logging': False,
          'obdMultiplexing': True,
          'request': [b'"\xf1\x88'],
          'responseAddress': 1831,
          'subAddress': 0},
         {'address': 1858,
          'brand': 'nissan',
          'bus': 1,
          'ecu': 'eps',
          'fwVersion': b'6CA2B\xa9A\x02\x02G8A89P90D6A\x00\x00\x01\x80',
          'logging': True,
          'obdMultiplexing': True,
          'request': [b'\x10\x81', b'!\x83'],
          'responseAddress': 1890,
          'subAddress': 0},
         {'address': 416993521,
          'brand': 'nissan',
          'bus': 1,
          'ecu': 'gateway',
          'fwVersion': b'284U29HE0A',
          'logging': True,
          'obdMultiplexing': True,
          'request': [b'"\xf1\x88'],
          'responseAddress': 417001936,
          'subAddress': 0},
         {'address': 1799,
          'brand': 'nissan',
          'bus': 1,
          'ecu': 'fwdCamera',
          'fwVersion': b'284N86CA1D',
          'logging': True,
          'obdMultiplexing': True,
          'request': [b'"\xf1\x88'],
          'responseAddress': 1831,
          'subAddress': 0},
         {'address': 2016,
          'brand': 'ford',
          'bus': 1,
          'ecu': 'engine',
          'fwVersion': b'237109HE2B',
          'logging': True,
          'obdMultiplexing': True,
          'request': [b'>\x00', b'"\xf1\x88'],
          'responseAddress': 2024,
          'subAddress': 0}],
'carName': 'mock',
```

**Comment by jyoung8607** [comment]
Indeed all of those entries are present. One of the queries is coming back tagged as Ford, but I'm not sure if that's the problem.

I'll need to see the route to dig into it further. The route ID you gave above isn't marked public. If you can mark it public, or make another route that you're willing to mark public if that one contains privacy relevant locations, I'll take a look. We'll get support merged one way or another.

**Comment by JtMotoX** [comment]
Here is a public route from OP master which did not detect the car.

`8864973010c8382c/0000000b--f0fc564584`

**Pull request closed without merging**
