### PR TITLE
wheel sensor error bit toyota

### PR DESCRIPTION
**Pull request by wocsor**

### CODE REVIEW

**Comment by pd0wm** [comment]
Can you use the same naming as the speeds, so `SENSOR_ERROR_FL`?

**Comment by wocsor** [comment]
Done

**Comment by pd0wm** [comment]
Is it also present on TSS2? Is there a good way to trigger an error?

**Comment by wocsor** [comment]
it should be present on all Toyotas with ABS, but i don't have a TSS2 car to test this on. you can trigger an error by unplugging a sensor, but i'm not sure if it's able to detect anything outside of an open circuit

**Pull request closed without merging**
