### PR TITLE
Added CRUISE_STATE value 11 description (timer_3sec)

### PR DESCRIPTION
**Pull request by briskspirit**
Added description for CRUISE_STATE value 11 : 3 seconds waiting timer. Will switch cruise state to standstill (7) after 3 seconds.
Added description for CRUISE_STATE value 9 : set cruise speed higher.
Added description for CRUISE_STATE value 10 : set cruise speed lower.

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Let's also add a comment that goes into more detail about the states.

**Comment by briskspirit** [comment]
Where do you want to add it? As a CM_ SG_ value?

**Comment by adeebshihadeh** [comment]
Yes

**Comment by briskspirit** [comment]
Ok no problem, will add tomorrow.

**Comment by briskspirit** [comment]
Comment was added. Sorry for the delay.

**Pull request merged**
