### PR TITLE
Add DBC for JDM Honda Fit Hybrid 2018

### PR DESCRIPTION
**Pull request by AravindaDP**
_dual_can_nidec_2018.dbc added as modified version of _honda_2017.dbc
since JDM Fit Hybrid use different brake message (Can be use for
Clarity as well)

### CODE REVIEW

**Comment by rbiasini** [comment]
you need to run `generator.py` to generate the final dbc file.
thanks.

**Comment by AravindaDP** [comment]
@rbiasini, done. Thanks for pointing out.
Let me know if any more details required. Thanks

**Comment by energee** [comment]
Should we add "JDM" or or relevant descriptor to this DBC? I guess US doesn't have Fit hybrid?

**Comment by AravindaDP** [comment]
@energee I'm fine with that. Guess honda_fit_hybrid_2018_jdm_can and honda_fit_hybrid_2018_jdm_can_generated would do. (Following the naming of odyssey extreme Chinese version naming)
@rbiasini let me know if you think the same. I would be happy to rename and resubmit

**Comment by rbiasini** [comment]
I can merge as is, feel free to open a new PR with renaming.

**Comment by AravindaDP** [comment]
@rbiasini, OK Thanks. Let it be like this then.
Guess this get automatically included in openpilot repo on next release or so?

**Pull request merged**
