### PR TITLE
Added Corolla SPORT_ON message

### PR DESCRIPTION
**Pull request by ShaneSmiskol**

### CODE REVIEW

**Comment by legonigel** [comment]
This file is automatically generated. Changes to this file will be overwritten next time the generator is run. Please edit the files in `generator/toyota` then run `generator\generator.py` to regenerate the `.dbc` files.

**Comment by ShaneSmiskol** [comment]
@legonigel Gotcha, I wasn't aware that Cabana wouldn't do this for me by itself. I updated and re-generated the correct files.

**Comment by ShaneSmiskol** [comment]
Any updates?

**Comment by ShaneSmiskol** [comment]
Closing to re-fork

**Pull request closed without merging**
