### PR TITLE
Parse DBCs dynamically

### PR DESCRIPTION
**Pull request by deanlee**
resolve https://github.com/commaai/opendbc/issues/374

### CODE REVIEW

**Comment by deanlee** [comment]
the execution time of `ensure_dbc` is 3-5 ms.

**Comment by pd0wm** [comment]
This will break CAN/DBC parsing in plotjuggler, since we only link against the C++ version of canparser, which would no longer have any DBC files. Can we move over the parsing logic to C++ as well without introducing a lot of new code?

**Comment by deanlee** [comment]
I'll try

**Comment by pd0wm** [comment]
Thanks! The use case for dynamic parsing is twofold:
1) Reduce openpilot build time and release size by not compiling all dbc files
2) Dynamic parsing in plotjuggler so we don't have to ship a plugin update every time the DBCs change and support for your own DBC files.

**Comment by deanlee** [comment]
Thanks for the explanation. I know what to do next.

**Comment by deanlee** [comment]
test_dbc_exceptions.py can't catch c++ runtime_error exceptions. comment it out for now

**Comment by adeebshihadeh** [comment]
I opened https://github.com/commaai/openpilot/pull/20741 to run the openpilot CI as a quick check and a bunch of the tests are failing.

**Comment by deanlee** [comment]
fixing

**Comment by adeebshihadeh** [comment]
Feel free to open a new PR against openpilot if you want to run the tests

**Comment by adeebshihadeh** [comment]
I see this is passing the openpilot tests now. We'll review and get this in for 0.8.5!

**Review by adeebshihadeh — COMMENTED** [review]
Can you also update the PlotJuggler plugins to use this? It should use BASEDIR to lookup the DBCs like it does for the cereal schema with `log.capnp`.

**Comment by adeebshihadeh** [comment]
Any reason this is still a draft? Don't worry about the PlotJuggler side, I can take care of that.

**Comment by deanlee** [comment]
> Any reason this is still a draft? Don't worry about the PlotJuggler side, I can take care of that.

That's great. then i think it's ready for review

**Comment by adeebshihadeh** [comment]
Thanks @deanlee! Continued in #602

**Pull request closed without merging**
