### PR TITLE
Toyota: Follow Distance Signal

### PR DESCRIPTION
**Pull request by cydia2020**
Used by the stock PCM adaptive cruise control to determine how close the lead should be followed. This changes with each press of the distance button, and cycles from 1 to 2 to 3.

### CODE REVIEW

**Comment by cydia2020** [comment]
This is different to `DISTANCE_LINES` in `0x399`, this signal always reflects the follow distance no matter if the distance setting display pops-up or not. `DISTANCE_LINES` is not 0 when the distance button is pressed.

**Comment by sshane** [comment]
Nice, so I'm guessing this is available on all TSS cars?

**Comment by cydia2020** [comment]
Still need to verify this, but it should be available on all Toyotas.

**Comment by sshane** [comment]
Thanks for the PR! Looks good against a TSSP Corolla and TSS2 Camry Hybrid

**Pull request merged**
