### PR TITLE
GM brake pedal position sensors and normalized/scaled brake/decel signal.

### PR DESCRIPTION
**Pull request by qadmus**
Pending tests:
- position or torque?
- does regen affect these signals?

### CODE REVIEW

**Comment by qadmus** [comment]
image

**Comment by adeebshihadeh** [comment]
Still want to get this merged? If the signals aren't used in openpilot, the definitions don't have to be perfect.

**Comment by qadmus** [comment]
I'll clean this up and ship it.

**Comment by qadmus** [comment]
Yeah this works fine for now. Not able to playthrough old preserved routes on cabana in the last few days.

**Comment by adeebshihadeh** [comment]
If you're still having issues with cabana, can you open an issue at https://github.com/commaai/cabana?

**Pull request merged**
