### PR TITLE
Add Toyota Odometer Reading to Toyota DBCs

### PR DESCRIPTION
**Pull request by nelsonjchen**
The unit is dependent on unit setting.

PS: Cabana currently doesn't parse the last comment's terminator correctly.

### CODE REVIEW

**Comment by nelsonjchen** [comment]
Bizzare, not sure how the generator can differ. It's clean on mine. I'll look into this later.

**Comment by pd0wm** [comment]
You need to rebase with master and rerun the generator. A new DBC file was added (`lexus_nx300_2018_pt_generated.dbc`) causing the test to fail.

**Comment by nelsonjchen** [comment]
@pd0wm Thanks! That was indeed it.

**Comment by jono-radar** [comment]
Hello, I want to test lexus_rx_hybrid_2017_pt_generated.dbc on my vehicle, but I only see two messages over OBD2 on a PeakCan USB adapter.  How to I get access to the full set of messages?

**Comment by nelsonjchen** [comment]
@jono-radar You should have made an explicit issue in this repo rather than *just commenting on a random unrelated issue which is not great GitHub etiquette*. OpenDBC is probably most prominently used by Openpilot but that doesn't mean it is openpilot only. 

That said, you should know there's likely a CAN Gateway that blocks these kinds of messages to the OBD2 port. In openpilot, users are observing the traffic behind the forward-facing camera which is less filtered than the traffic to the OBD2 port. That's likely why you aren't seeing it.

**Pull request merged**
