### PR TITLE
body: remove orientation/angular velocity checks

### PR DESCRIPTION
**Pull request by fredyshox**

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
If these are still lists, this is still necessary. (This is why I wanted to remove lists in `livePose`)

**Comment by fredyshox** [comment]
why does this check exist? those values are not used anywhere and this is the only carController referencing them

**Comment by fredyshox** [comment]
@adeebshihadeh from what i see, this is a leftover from self-balacing code: https://github.com/commaai/openpilot/blob/16ec56398c3b23db917eb0f9474aa9f6ed2a459c/selfdrive/car/body/carcontroller.py#L48 so can be deleted

**Comment by adeebshihadeh** [comment]
@sshane let's deprecate from carControl then?

**Pull request merged**
