### PR TITLE
Toyota Pedal Support

### PR DESCRIPTION
**Pull request by wocsor**
add pedal signal with toyota scaling to all dbc

### CODE REVIEW

**Comment by rbiasini** [comment]
@wocsor , what are the `.DS_store` files? not needed, right?

**Comment by wocsor** [comment]
Not at all. Those are because I used a Mac and forgot to set up gitignore.. my bad

**Comment by rbiasini** [comment]
Cool. Wil merge when they are removed. Thanks!

**Comment by wocsor** [comment]
That should be it. Sorry about those

**Pull request merged**
