### PR TITLE
VW PQ: EPB_1 cleanup and sort

### PR DESCRIPTION
**Pull request by FLcruising**
Sort the messages.

### CODE REVIEW

**Comment by sshane** [comment]
@jyoung8607 look good?

**Comment by jyoung8607** [comment]
I agree with the main substance of the EPB changes, but this also includes a duplicate of the #824 work. @FLcruising can you rebase after that gets merged, and then maybe pull in the relevant VALs the same way you did on the other PR? Will review in detail after those updates.

**Comment by FLcruising** [comment]
> I agree with the main substance of the EPB changes, but this also includes a duplicate of the #824 work. @FLcruising can you rebase after that gets merged, and then maybe pull in the relevant VALs the same way you did on the other PR? Will review in detail after those updates.

Sure, no problem. Sorry for the duplicate; it was because I kept editing the same DBC.

**Comment by FLcruising** [comment]
See #837

**Pull request closed without merging**
