### PR TITLE
Add empty nidec brake command frame to CIVIC_BOSCH (normal and diesel) for long control

### PR DESCRIPTION
**Pull request by csouers**
This is needed for positive acceleration control via CAN (ignored by the ECM without it).

### CODE REVIEW

**Comment by csouers** [comment]
@pd0wm Ready for review. Happy to address any comments that you may have.

**Comment by pd0wm** [comment]
Sorry, didn't see this one. As with the RDW message, there is no need to define SETME_X00s.

**Comment by csouers** [comment]
> Sorry, didn't see this one. As with the RDW message, there is no need to define SETME_X00s.

Done!

**Comment by Vaggysag** [comment]
This has been working great for me, no issues. Please merge this whenever possible

**Pull request merged**
