### PR TITLE
toyota nodsu cars radar support

### PR DESCRIPTION
**Pull request by Smartype**

### CODE REVIEW

**Comment by Smartype** [comment]
ACC_CONTROL_COPY: 
1. Why add this msg: canfilter board detection; logging and debugging; DISTANCE button
2. Why not 0x2ff: 0x2ff msg is used on stock system on nodsu cars. Between camera and radar

ACC_CONTROL_SAFE: with Camry SE/LE, we can by pass the 28mph speed lockout in pcm with ACC_TYPE hack. But there is another speed lock in the ABS module. When below 15 mph, stock ACC is on, but brake request is ignored by ABS. Which is dangerous. Which this msg, the canfilter board force the PCM to quit ACC mode when OP is engaged while speed drop to 15mph. Anyway, the canfilter board accepts ACC_CONTROL as well.

**Comment by adeebshihadeh** [comment]
Let's split this up. The radar DBC should go in its own PR. The stuff for your custom HW should go in the community DBC.

**Comment by Smartype** [comment]
What is the community DBC? These two msg (ACC_CONTROL_COPY, ACC_CONTROL_SAFE) will be used in the OP code. 

> Let's split this up. The radar DBC should go in its own PR. The stuff for your custom HW should go in the community DBC.

**Comment by cydia2020** [comment]
> What is the community DBC? These two msg (ACC_CONTROL_COPY, ACC_CONTROL_SAFE) will be used in the OP code.
> 
> > Let's split this up. The radar DBC should go in its own PR. The stuff for your custom HW should go in the community DBC.

Community dbc is the one in the generator. `opendbc/generator/toyota/_comma.dbc`

**Comment by eFiniLan** [comment]
the radar message doesn't match with my C-HR :(

**Comment by Smartype** [comment]
> the radar message doesn't match with my C-HR :(
> 
> https://cabana.comma.ai/?route=6e67d7f1974fea9a%7C2022-05-19--13-34-27&exp=1686474333&sig=sLY7sn7DzthvA4cx%2F0yN%2F%2Flv8%2Bv%2FcRDbstqY2ZsmkZE%3D&max=12&url=https%3A%2F%2Fchffrprivate.azureedge.net%2Fchffrprivate3%2Fv2%2F6e67d7f1974fea9a%2F6a33070a9f3ccdce086f8fe6dcb232c7_2022-05-19--13-34-27

There is a CH-R route: https://cabana.comma.ai/?route=21dc35ba8df586fb%7C2022-06-10--13-11-15&exp=1686419022&sig=O%2B61rFn%2FGTU%2FgRm2dIYg%2FfAg4qfBzJlP1AtzR0OS5YU%3D&max=-1&url=https%3A%2F%2Fchffrprivate.azureedge.net%2Fchffrprivate3%2Fv2%2F21dc35ba8df586fb%2Fb5426740022898edaaec8e11533db134_2022-06-10--13-11-15

You can see lots of leading 0x3f on CAN 1, that is invalid track.

What is your CH-R trim/model? Is it a very new model which use the same radar with new RAV4?

**Comment by eFiniLan** [comment]
> > the radar message doesn't match with my C-HR :(
> > https://cabana.comma.ai/?route=6e67d7f1974fea9a%7C2022-05-19--13-34-27&exp=1686474333&sig=sLY7sn7DzthvA4cx%2F0yN%2F%2Flv8%2Bv%2FcRDbstqY2ZsmkZE%3D&max=12&url=https%3A%2F%2Fchffrprivate.azureedge.net%2Fchffrprivate3%2Fv2%2F6e67d7f1974fea9a%2F6a33070a9f3ccdce086f8fe6dcb232c7_2022-05-19--13-34-27
> 
> There is a CH-R route: https://cabana.comma.ai/?route=21dc35ba8df586fb%7C2022-06-10--13-11-15&exp=1686419022&sig=O%2B61rFn%2FGTU%2FgRm2dIYg%2FfAg4qfBzJlP1AtzR0OS5YU%3D&max=-1&url=https%3A%2F%2Fchffrprivate.azureedge.net%2Fchffrprivate3%2Fv2%2F21dc35ba8df586fb%2Fb5426740022898edaaec8e11533db134_2022-06-10--13-11-15
> 
> You can see lots of leading 0x3f on CAN 1, that is invalid track.
> 
> What is your CH-R trim/model? Is it a very new model which use the same radar with new RAV4?

Quite possibly, mine is MY2021... I guess its a no go then :)

**Pull request closed without merging**
